language: python
python:
    - "2.6"
    - "2.7"

# command to install dependencies
install: "pip install -r docker/python/requirements.txt"
# command to run tests
script: python php_opcache_exporter.py
# use new travis-ci container-based infrastructure 
sudo: false

